// <auto-generated />
using System;
using Legacy.Maliev.CatalogService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Legacy.Maliev.CatalogService.Data.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260715030219_InitialPostgresCompatibility")]
    partial class InitialPostgresCompatibility
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Legacy.Maliev.CatalogService.Domain.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("Color", (string)null);
                });

            modelBuilder.Entity("Legacy.Maliev.CatalogService.Domain.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Continent")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Iso2")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("ISO2");

                    b.Property<string>("Iso3")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("ISO3");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("Country", (string)null);
                });

            modelBuilder.Entity("Legacy.Maliev.CatalogService.Domain.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("Currency", (string)null);
                });

            modelBuilder.Entity("Legacy.Maliev.CatalogService.Domain.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Afnor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("AFNOR");

                    b.Property<string>("Aisi")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("AISI");

                    b.Property<string>("Ams")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("AMS");

                    b.Property<string>("Astm")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ASTM");

                    b.Property<string>("Bts")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("BTS");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("CurrencyID");

                    b.Property<decimal?>("DensityKilogramPerCubicMeter")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("Din")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DIN");

                    b.Property<string>("En")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("EN");

                    b.Property<decimal?>("HardnessBrinell")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal?>("HardnessKnoop")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal?>("HardnessRockwellA")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal?>("HardnessRockwellB")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal?>("HardnessRockwellC")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal?>("HardnessVickers")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<string>("Jis")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("JIS");

                    b.Property<decimal?>("MachinabilityPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("Machinable")
                        .HasColumnType("boolean");

                    b.Property<string>("ManufacturerReference")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MaterialGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("MaterialGroupID");

                    b.Property<string>("MaterialNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("PricePerKilogram")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("Printable")
                        .HasColumnType("boolean");

                    b.Property<string>("Sae")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SAE");

                    b.Property<decimal?>("ShearModulusGigaPascal")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<string>("Sis")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SIS");

                    b.Property<decimal?>("TensileStrengthUltimateGigaPascal")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal?>("TensileStrengthYieldMegaPascal")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal?>("ThermalConductivityWattPerMeterKelvin")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<string>("Uni")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("UNI");

                    b.Property<string>("Uns")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("UNS");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("URL");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("MaterialGroupId")
                        .HasDatabaseName("IX_Material_MaterialGroupID");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Material_Name");

                    b.ToTable("Material", (string)null);
                });

            modelBuilder.Entity("Legacy.Maliev.CatalogService.Domain.MaterialGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("MaterialGroup", (string)null);
                });

            modelBuilder.Entity("Legacy.Maliev.CatalogService.Domain.MaterialHasColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorId")
                        .HasColumnType("integer")
                        .HasColumnName("ColorID");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer")
                        .HasColumnName("MaterialID");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("MaterialId", "ColorId")
                        .HasDatabaseName("IX_MaterialHasColor_MaterialID_ColorID");

                    b.ToTable("MaterialHasColor", (string)null);
                });

            modelBuilder.Entity("Legacy.Maliev.CatalogService.Domain.MaterialHasSupplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer")
                        .HasColumnName("MaterialID");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer")
                        .HasColumnName("SupplierID");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId", "SupplierId")
                        .HasDatabaseName("IX_MaterialHasSupplier_MaterialID_SupplierID");

                    b.ToTable("MaterialHasSupplier", (string)null);
                });

            modelBuilder.Entity("Legacy.Maliev.CatalogService.Domain.MaterialHasSurfaceFinish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer")
                        .HasColumnName("MaterialID");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("SurfaceFinishId")
                        .HasColumnType("integer")
                        .HasColumnName("SurfaceFinishID");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("SurfaceFinishId");

                    b.HasIndex("MaterialId", "SurfaceFinishId")
                        .HasDatabaseName("IX_MaterialHasSurfaceFinish_MaterialID_SurfaceFinishID");

                    b.ToTable("MaterialHasSurfaceFinish", (string)null);
                });

            modelBuilder.Entity("Legacy.Maliev.CatalogService.Domain.SurfaceFinish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("SurfaceFinish", (string)null);
                });

            modelBuilder.Entity("Legacy.Maliev.CatalogService.Domain.Material", b =>
                {
                    b.HasOne("Legacy.Maliev.CatalogService.Domain.MaterialGroup", "MaterialGroup")
                        .WithMany("Materials")
                        .HasForeignKey("MaterialGroupId")
                        .IsRequired()
                        .HasConstraintName("FK_Material_MaterialGroup");

                    b.Navigation("MaterialGroup");
                });

            modelBuilder.Entity("Legacy.Maliev.CatalogService.Domain.MaterialHasColor", b =>
                {
                    b.HasOne("Legacy.Maliev.CatalogService.Domain.Color", "Color")
                        .WithMany("MaterialHasColors")
                        .HasForeignKey("ColorId")
                        .IsRequired()
                        .HasConstraintName("FK_MaterialHasColor_Color");

                    b.HasOne("Legacy.Maliev.CatalogService.Domain.Material", "Material")
                        .WithMany("MaterialHasColors")
                        .HasForeignKey("MaterialId")
                        .IsRequired()
                        .HasConstraintName("FK_MaterialHasColor_Material");

                    b.Navigation("Color");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Legacy.Maliev.CatalogService.Domain.MaterialHasSupplier", b =>
                {
                    b.HasOne("Legacy.Maliev.CatalogService.Domain.Material", "Material")
                        .WithMany("MaterialHasSuppliers")
                        .HasForeignKey("MaterialId")
                        .IsRequired()
                        .HasConstraintName("FK_MaterialHasSupplier_Material");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Legacy.Maliev.CatalogService.Domain.MaterialHasSurfaceFinish", b =>
                {
                    b.HasOne("Legacy.Maliev.CatalogService.Domain.Material", "Material")
                        .WithMany("MaterialHasSurfaceFinishes")
                        .HasForeignKey("MaterialId")
                        .IsRequired()
                        .HasConstraintName("FK_MaterialHasSurfaceFinish_Material");

                    b.HasOne("Legacy.Maliev.CatalogService.Domain.SurfaceFinish", "SurfaceFinish")
                        .WithMany("MaterialHasSurfaceFinishes")
                        .HasForeignKey("SurfaceFinishId")
                        .IsRequired()
                        .HasConstraintName("FK_MaterialHasSurfaceFinish_SurfaceFinish");

                    b.Navigation("Material");

                    b.Navigation("SurfaceFinish");
                });

            modelBuilder.Entity("Legacy.Maliev.CatalogService.Domain.Color", b =>
                {
                    b.Navigation("MaterialHasColors");
                });

            modelBuilder.Entity("Legacy.Maliev.CatalogService.Domain.Material", b =>
                {
                    b.Navigation("MaterialHasColors");

                    b.Navigation("MaterialHasSuppliers");

                    b.Navigation("MaterialHasSurfaceFinishes");
                });

            modelBuilder.Entity("Legacy.Maliev.CatalogService.Domain.MaterialGroup", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("Legacy.Maliev.CatalogService.Domain.SurfaceFinish", b =>
                {
                    b.Navigation("MaterialHasSurfaceFinishes");
                });
#pragma warning restore 612, 618
        }
    }
}
